import type { Metadata } from "next";
import './globals.css'
import NewNavBar from "@/components/NavBar/NewNavBar";
import FooterNew2 from "@/components/FooterNew/FooterNew2";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         <NewNavBar />
        {children} 
         <FooterNew2 /> 

      </body>
    </html>
  );
}
